window.APP_CONFIG = {
  baseUrl: "http://localhost:5050",
  api: {
    views: { path: "/views", method: "GET" },
    nodeTypes: { path: "/node-types", method: "POST" },
    legends: { path: "/node-legends", method: "POST" },
    items: { path: "/items", method: "POST" },
    expand: { path: "/expand", method: "POST" },
    masterNodes: { path: "/master-nodes", method: "GET" },
    groupNodes: { path: "/group-nodes", method: "GET" },
    updateMasterNode: { path: "/master-nodes/update", method: "POST" },
    masterRelations: { path: "/master-relations", method: "GET" },
    saveRelation: { path: "/master-relations/save", method: "POST" },
    deleteRelation: { path: "/master-relations/delete", method: "POST" },
  },
  defaults: {
    maxItems: 20,
    maxNodes: 200,
    autoExpandDepth: 1,
    autoExpandMinDepth: 1,
    autoExpandMaxDepth: 12,
  },
  defaultLang: "en",
  showLanguageSelector: true,
  showTimelineButton: false,
  userId: "demo-user",
};
